config:
  cluster:
    path:
    - cluster-config/

  namespaces:
    path:
    - config/{label=team}/*/
    defaultpath:
    - config/_default/
    - config/{label=team}/_default/

management:
  cluster:
    clusterroles:
      cleanup: true

    clusterrolebindings:
      cleanup: true

    podsecuritypolicies:
      cleanup: true

    storageclasses:
      cleanup: true

    namespace:
      cleanup: true

  namespaces:
  - name: "*"
    configmaps:
      cleanup: true

    limitranges:
      cleanup: true

    networkpolicies:
      cleanup: true

    poddisruptionbudgets:
      cleanup: true

    podpresets:
      enabled: false
      cleanup: true

    resourcequotas:
      cleanup: true

    rolebindings:
      cleanup: true

    roles:
      cleanup: true

    serviceaccounts:
      cleanup: true
