config:
  cluster:
    path:
    - cluster-config/

  namespaces:
    path:
    - config/{label=team}/*/
    defaultpath:
    - config/_default/
    - config/{label=team}/_default/
    cleanup: true

  clusterroles:
    cleanup: true

  clusterrolebindings:
    cleanup: true

  serviceaccounts:
    cleanup: true

  rolebindings:
    cleanup: true

  resourcequotas:
    cleanup: true

  limitranges:
    cleanup: true

  configmap:
    cleanup: true
