config:
  cluster:
    path:
    - cluster-config/

  namespaces:
    path:
    - config/{label=team}/*/
    defaultpath:
    - config/_default/
    - config/{label=team}/_default/
    labels:
    - name: foobar1
      value: barfoo
    - name: foobar2
      value: barfoo
      fileexists: config/{label=team}/{namespace}/.foobar
    - name: foocontent
      filecontent: config/{label=team}/{namespace}/.foocontent
    - name: last-update
      dateformat: 2006-01-02
    annotations:
    - name: foobar1
      value: barfoo
    - name: foobar2
      value: barfoo
      fileexists: config/{label=team}/{namespace}/.foobar
    - name: foocontent
      filecontent: config/{label=team}/{namespace}/.foocontent

management:
  cluster:
    clusterroles:
      cleanup: true

    clusterrolebindings:
      cleanup: true

    podsecuritypolicies:
      cleanup: true

    storageclasses:
      cleanup: true

    namespace:
      cleanup: true

  namespaces:
  - name: "team1-*"
    configmaps:
      cleanup: true

    limitranges:
      cleanup: true

  - name: "*"
    configmaps:
      cleanup: true

    limitranges:
      cleanup: true
      blacklist:
      - /foobar.+/
      whitelist:
      - /mem.+/
      - mem*
      - barfoo*

    networkpolicies:
      cleanup: true

    poddisruptionbudgets:
      cleanup: true

    podpresets:
      enabled: false
      cleanup: true

    resourcequotas:
      cleanup: true

    rolebindings:
      cleanup: true

    roles:
      cleanup: true

    serviceaccounts:
      cleanup: true

